# Uncomment this line to define a global platform for your project
 platform :ios, '9.0'

target 'NetworkLayer' do
# Comment this line if you're not using Swift and don't want to use dynamic frameworks
use_frameworks!
pod 'SDWebImage', '~>3.8'
# Pods for NetworkLayer

target 'NetworkLayerTests' do
inherit! :search_paths
# Pods for testing
end

end

